compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fsdp_config: {}
machine_rank: 0
main_process_ip: ''
main_process_port: 12332
main_training_function: main
mixed_precision: 'no'
num_machines: 2
num_processes: 8
use_cpu: false

