name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: [uses: fastai/workflows/quarto-ghp@master, run: sudo apt-get install libsndfile-dev]
